// Auto-generated by scripts/fetch-software-versions.mjs during build.
// Do not edit manually.

export const AUTHENTIC_SOFTWARE = {
  apple: "27.2",
  samsung: "S928BXXS6DZH2",
  google: "HDR+ 1.0.641377609zdh",
} as const;
